version: "3.4"

services:
    gas:
        image: gas
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/workdir
        working_dir: /workdir
        command: tail -f /dev/null
