version: "3.4"

services:
    bell-ringer:
        image: gas
        build:
            context: .
            dockerfile: Dockerfile
        container_name: "gas-build"
        tty: true
        volumes:
            - "../src:/opt/src"
